
name: preach
on: 
    workflow_dispatch:
    schedule:
      - cron: '0 14 * * *'

    watch:
        types: [ started ]

jobs:
   build:
       runs-on: windows-latest
       steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.9
            uses: actions/setup-python@v2
            with:
                python-version: 3.9.1
          - name: install pip packages
            run: python -m pip install --upgrade pip
          - name: install lxml
            run: pip install lxml
          - name: install requests
            run: pip install requests  
          - name: run preach
            run: python Preaching.py
